Repository srknzl/bigdecimal.js, pull requests merged in 2022-01, with the labels that each got.

#25 Do not use bigint literals to enable usage in non-nodejs environments with a polyfill
  README.md
  benchmarks/test_numbers.js
  package.json
  src/bigdecimal.ts
Labels: enhancement

#32 Update dependencies
  package.json
Labels: dependencies

#31 Created Markdown checker
  .github/workflows/markdown_link_checker.yml
Labels: documentation, enhancement

#33 Fix broken links
  util/README.md
Labels: documentation
